# Generated by Django 4.0.1 on 2022-02-03 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('add_breed', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('height', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('activity', models.CharField(max_length=100)),
                ('meal', models.CharField(max_length=100)),
                ('dislike', models.CharField(max_length=100)),
                ('allergies', models.CharField(max_length=100)),
                ('prefer_food', models.CharField(max_length=100)),
                ('help_required', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
